services:
  postgres-db:
    image: postgres:16-alpine
    container_name: my-market-postgres
    environment:
      POSTGRES_DB: my-market-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-market-network

  my-market-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-market-app
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/my-market-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - my-market-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  my-market-network:
    driver: bridge